### ISSUE TITLE
Swift: Testing to see if XcodeColors is installed and enabled

### ISSUE THREAD

**Issue by raphaklr** [robbiehanson/XcodeColors#40]
In the README, you provided a code snippet in C for testing, if XcodeColors is installed and enabled. How would that code look like in Swift?

**Comment by bm842** [comment]
I would have expected this to work: 
let str = String.fromCString(getenv("XcodeColors")) // String?
It reports nil although the plugin is working
doing setenv("XcodeColors", "NO", 0) does not disable it.

**Comment by silan-liu** [comment]
```
let xcode_colors = getenv("XcodeColors")
 if strcmp(xcode_colors, "YES") == 0 {
     return true
}
return false
```

try this

**Comment by jacobjohnston** [comment]
I'm not getting clear behavior on this either. In Swift, I would expect the code to check whether XcodeColors was installed to be something like this:

```Swift
let canColor = NSProcessInfo().environment["XcodeColors"] == "YES"
````

But, that environment variable is always nil. However, if I go set it manually, it can read it fine.

```Swift
setenv("XcodeColors", "YES", 0)
let canColor = NSProcessInfo().environment["XcodeColors"] == "YES"
````

The colors DO work, I'm just not able to see if the plugin is installed. Any tips?

**Comment by jacobjohnston** [comment]
Nevermind, I understand now. I'm working on an iOS app. The environment variables won't work in iOS because those environment variables are defined on my Mac, not on my iDevice or my simulator. That's a bit of a bummer - I want a way for this to "just work" for the developers that have XcodeColors installed, and gracefully fall back to normal logging for developers that don't. Is there any way to have user-specific environment variables defined for the simulator?

**Comment by LightMan** [comment]
Combined with cocoalumberjack, old C style \o/
```swift
        DDLog.addLogger(DDTTYLogger.sharedInstance()) // TTY = Xcode console
        let xcode_colors = getenv("XcodeColors");
        if xcode_colors != nil && strcmp(xcode_colors, "YES") == 0 {
            DDTTYLogger.sharedInstance().colorsEnabled = true;
        }
```

**Comment by nesevis** [comment]
Using this with Alcatraz getenv("XcodeColors") never works. I've implemented the check both with Swift and with Objective C—  it is never enabled.

Tips?
