### ISSUE TITLE
Not working in Xcode 7.3

### ISSUE THREAD

**Issue by anzhehong** [robbiehanson/XcodeColors#82]
I used XcodeColors for a while and many thx to your contribution~
However, when I get Xcode 7.3 today, it seems that my customer colors disappear... What should I do?

**Comment by skreutzberger** [comment]
I fixed the issue because SwiftyBeaver Logger depends on a working XcodeColors, too and released a prebuilt version. It uses a solution provided by #80 

Just download the already **prebuilt** version of XcodeColors which **works on Xcode 7.3** from [SwiftyBeaver's Github repo](https://github.com/SwiftyBeaver/SwiftyBeaver#no-colors). Just search for "No colors?" in the README to get an explanation how to install.

**Comment by anzhehong** [comment]
THX a lot

发自我的 iPhone

**Comment by andrewzboard** [comment]
Worked for me. How could I have lived without the colors? Thanks!
